// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGVCFh5otQeId0h928u7FDLaa_-TMSaM',
    appId: '1:932532353645:web:ae2d5024433c07acaf5d64',
    messagingSenderId: '932532353645',
    projectId: 'tracking-8d231',
    authDomain: 'tracking-8d231.firebaseapp.com',
    storageBucket: 'tracking-8d231.firebasestorage.app',
    measurementId: 'G-3L7RM3C5QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNb71V0PyDEk0MVT8FTgIow5hJHsSE2BE',
    appId: '1:932532353645:android:290c811f80827f06af5d64',
    messagingSenderId: '932532353645',
    projectId: 'tracking-8d231',
    storageBucket: 'tracking-8d231.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxyytjCY4rBphDy2YMCUlQMZ8mSY_NGZo',
    appId: '1:932532353645:ios:7ff793ab9f21ec5eaf5d64',
    messagingSenderId: '932532353645',
    projectId: 'tracking-8d231',
    storageBucket: 'tracking-8d231.firebasestorage.app',
    iosBundleId: 'com.example.gmapTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxyytjCY4rBphDy2YMCUlQMZ8mSY_NGZo',
    appId: '1:932532353645:ios:7ff793ab9f21ec5eaf5d64',
    messagingSenderId: '932532353645',
    projectId: 'tracking-8d231',
    storageBucket: 'tracking-8d231.firebasestorage.app',
    iosBundleId: 'com.example.gmapTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhGVCFh5otQeId0h928u7FDLaa_-TMSaM',
    appId: '1:932532353645:web:c4a653d6792d7164af5d64',
    messagingSenderId: '932532353645',
    projectId: 'tracking-8d231',
    authDomain: 'tracking-8d231.firebaseapp.com',
    storageBucket: 'tracking-8d231.firebasestorage.app',
    measurementId: 'G-WV69GFX91N',
  );

}